In [4]:
import csv
import os
import pandas as pd

from sqlalchemy import create_engine
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy import String, Integer, Double, PrimaryKeyConstraint

In [ ]:
# look at data to determine the db schema

dfs: list = []

data_dir: str = "ml-latest-small"
paths: list = [
    os.path.join(data_dir, path) for path in os.listdir(data_dir) if path[-3:] == "csv"
]
[dfs.append(pd.read_csv(path)) for path in paths]

[None, None, None, None]

In [ ]:
print(paths[0])
dfs[0].head(3)

ml-latest-small\links.csv

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0

In [35]:
print(paths[1])
dfs[1].head(3)

ml-latest-small\movies.csv

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance

In [31]:
print(paths[2])
dfs[2].head(3)

ml-latest-small\ratings.csv

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224

In [33]:
print(paths[3])
dfs[3].head(3)

ml-latest-small\tags.csv

   userId  movieId              tag   timestamp
0       2    60756            funny  1445714994
1       2    60756  Highly quotable  1445714996
2       2    60756     will ferrell  1445714992

In [34]:
[print(path) for path in paths]

ml-latest-small\links.csv
ml-latest-small\movies.csv
ml-latest-small\ratings.csv
ml-latest-small\tags.csv

[None, None, None, None]

In [ ]:
def show(path: str):
    print("\npath: ", path)
    df = pd.read_csv(path)
    print(df.head(3).to_dict())


list(map(show, paths))

path:  ml-latest-small\links.csv
{'movieId': {0: 1, 1: 2, 2: 3}, 'imdbId': {0: 114709, 1: 113497, 2: 113228}, 'tmdbId': {0: 862.0, 1: 8844.0, 2: 15602.0}}

path:  ml-latest-small\movies.csv
{'movieId': {0: 1, 1: 2, 2: 3}, 'title': {0: 'Toy Story (1995)', 1: 'Jumanji (1995)', 2: 'Grumpier Old Men (1995)'}, 'genres': {0: 'Adventure|Animation|Children|Comedy|Fantasy', 1: 'Adventure|Children|Fantasy', 2: 'Comedy|Romance'}}

path:  ml-latest-small\ratings.csv
{'userId': {0: 1, 1: 1, 2: 1}, 'movieId': {0: 1, 1: 3, 2: 6}, 'rating': {0: 4.0, 1: 4.0, 2: 4.0}, 'timestamp': {0: 964982703, 1: 964981247, 2: 964982224}}

path:  ml-latest-small\tags.csv
{'userId': {0: 2, 1: 2, 2: 2}, 'movieId': {0: 60756, 1: 60756, 2: 60756}, 'tag': {0: 'funny', 1: 'Highly quotable', 2: 'will ferrell'}, 'timestamp': {0: 1445714994, 1: 1445714996, 2: 1445714992}}

[None, None, None, None]

### DB schema

#### schema movie
- movie.links:
    - id: pk
    - id_movie: fk movies
    - imdbId: int unique
    - tmdbId: int unique

- movie.movies:
    - id: pk
    - title, varchar(512)

- movie.tags:
    - id: pk
    - id_movie: fk movies
    - id_user: fk users
    - tag: varchar(512)
    - timestamp: timestamp 

- movie.movie_genres:
    - id: pk
    - id_movie: fk movies
    - id_genre: fk genres

#### schema rating
- rating.ratings:
    - id: pk
    - id_movie: fk movies
    - id_user: fk users
    - rating: double(3,1)
    - timestamp: timestamp

#### schema user 
- users.users:
    - id: pk

#### schema enum
- enum.genres
    - id: pk
    - name: varchar(64)